parameters: {}

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            int $rateLimitMax: '%env(int:RATE_LIMIT_MAX)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    Predis\Client:
        arguments:
            - scheme: 'tcp'
              host:   '%env(REDIS_HOST)%'
              port:   '%env(int:REDIS_PORT)%'

when@test:
    services:
        _defaults:
            autowire: true
            autoconfigure: true
            public: true

        App\Tests\Stub\FakeRedisClient:
            public: true

        Predis\Client:
            alias: App\Tests\Stub\FakeRedisClient
            public: true